# Generated by Django 4.1 on 2022-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stall",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
