# Generated by Django 4.1 on 2022-10-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodies", "0002_stall_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="photo",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stall",
            name="photo",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu", name="category", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="menu",
            name="stall_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="foodies.stall",
            ),
        ),
    ]
