# Generated by Django 4.1 on 2022-11-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodies", "0003_menu_photo_stall_photo_alter_menu_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stall",
            name="category",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
