# Generated by Django 4.1 on 2023-03-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0007_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
